version: '3'
services:

  user-mysql:
     image: mysql:8.0.15
     network_mode: host
     ports:
       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_PASSWORD: root
       MYSQL_DATABASE: PlaceApp
       MYSQL_HOST: localhost
  user-mongo:
     image: mongo
     network_mode: host
     ports:
       - "27017:27017"
     environment:
       MONGO_DATABASE: capstoneDB
       MONGO_PORT: 27017
       MONGO_HOST: localhost

  userservice:
     image: user-service
     build: 
       context: UserService/
     depends_on:
       - user-mysql
     ports:
       - "9090:9090"
     network_mode: host
     restart: always
     
  companyreviewservice:
     image: companyreview-service
     build: 
       context: CompanyReviewsService/
     depends_on:
       - user-mongo
     ports:
       - "8080:8080"
     network_mode: host
     restart: always
     
  bookmarkservice:
     image: bookmark-service
     build: 
       context: BookMarkService/
     depends_on:
       - user-mongo
     ports:
       - "8082:8082"
     network_mode: host
     restart: always
     
  
       
