FROM java:8-jre
COPY ./target/CompanyReviewsService-0.0.1-SNAPSHOT.jar /usr/src/CompanyReviewsService-0.0.1-SNAPSHOT.jar
WORKDIR /usr/src
CMD ["java","-jar","CompanyReviewsService-0.0.1-SNAPSHOT.jar"]